"""removed project-subject relationship

Revision ID: 261cb0818ff3
Revises: 89987c2a8235
Create Date: 2024-01-03 19:56:06.611218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261cb0818ff3'
down_revision = '89987c2a8235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_subject_id', type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_project_subject_id', 'subject', ['subject_id'], ['id'])

    # ### end Alembic commands ###
