"""Added Flashcard model

Revision ID: 47ce19fe53be
Revises: fea8d042389a
Create Date: 2024-06-15 16:07:15.840667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ce19fe53be'
down_revision = 'fea8d042389a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('term', sa.VARCHAR(length=255), nullable=False),
    sa.Column('definition', sa.TEXT(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
