"""Change content column from Note model to JSON type

Revision ID: 52008ee9626d
Revises: c28df8edf8da
Create Date: 2024-11-18 12:02:59.073454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52008ee9626d'
down_revision = 'c28df8edf8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
