"""added relationship between projects and users

Revision ID: 89987c2a8235
Revises: 74c7d277f7b6
Create Date: 2024-01-02 15:59:24.666180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89987c2a8235'
down_revision = '74c7d277f7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_project_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
