"""Changed all created_date and modified_date instances to created_at and modified_at to maintain consistency

Revision ID: c28df8edf8da
Revises: 
Create Date: 2024-11-13 13:49:20.014295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28df8edf8da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_date')
        batch_op.drop_column('modified_date')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_date')
        batch_op.drop_column('modified_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
